apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: user-service
  annotations:
    key-auth.plugin.konghq.com: "key-auth-plugin"
spec:
  rules:
  - host: api.pongpong.io
    http:
      paths:
      - path: /user-service
        backend:
          serviceName: user-service
          servicePort: 80
---

apiVersion: configuration.konghq.com/v1
kind: KongIngress
metadata:
  name: user-service
proxy:
  path: /external
route:
  strip_path: true
---

apiVersion: v1
kind: Service
metadata:
  name: user-service-db
spec:
  ports:
  - port: 5432
  selector:
    type: db
    service: user

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    type: api
    service: user

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      type: db
      service: user
  template:
    metadata:
      labels:
        type: db
        service: user
    spec:
      containers:
        - name: db
          image: postgres:10.3
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: users
          ports:
            - containerPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      type: api
      service: user
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        type: api
        service: user
    spec:
      containers:
        - name: user
          image: outsideris/k8s-study-user-service:0.4
          env:
          - name: PORT
            value: "8080"
          - name: DB_HOST
            value: user-service-db
          - name: DB_PORT
            value: "5432"
          - name: DB_USERNAME
            value: postgres
          - name: DB_PASSWORD
            value: postgres
          - name: KONG_HOST
            value: http://kong-ingress-controller.kong:8001
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
          ports:
            - containerPort: 8080
              protocol: TCP
