openapi: 3.0.0
info:
  title: Users API
  description: users API for microservice x kubernetes study.
  version: 0.3.0

servers:
  - url: http://user-service/
    description: user service API

paths:
  /health:
    get:
      summary: health check

  /v1/signup:
    post:
      summary: add a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  format: password
              required:
                - username
                - password
      responses:
        '201':
          description: a created user
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: the result
                  key:
                    type: string
                    description: auth token

  /v1/login:
    post:
      summary: user login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                  format: password
              required:
                - username
                - password
      responses:
        '200':
          description: user info
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: the result
                  key:
                    type: string
                    description: auth token

  /v1/users/{id}:
    get:
      summary: Returns a user information.
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The user ID.
                  email:
                    type: string
                    description: The email.
                  created_at:
                    type: string
                    format: date-time
                    description: The created datetime.

  /v1/user:
    get:
      summary: Returns a logged in user information.
      parameters:
        - in: header
          name: X-Consumer-Custom-ID
          schema:
            type: integer
          required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The user ID.
                  email:
                    type: string
                    description: The email.
                  created_at:
                    type: string
                    format: date-time
                    description: The created datetime.
