openapi: 3.0.0
info:
  title: Users API
  description: users API for microservice x kubernetes study.
  version: 0.1.0

servers:
  - url: http://127.0.0.1:8080/v1/
    description: a local dev server  

paths:
  /signup:
    post:
      summary: add a new user
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
              required:
                - username
                - password
      responses:
        '201':
          description: a created user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The user ID.
                  username:
                    type: string
                    description: The username.
                  access_token:
                    type: string
                    description: The access token.
                  created_at:
                    type: string
                    format: date-time
                    description: The created datetime.

  /login:
    post:
      summary: user login
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                  format: password
              required:
                - username
                - password
      responses:
        '200':
          description: user info
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The user ID.
                  username:
                    type: string
                    description: The username.
                  access_token:
                    type: string
                    description: The access token.
                  created_at:
                    type: string
                    format: date-time
                    description: The created datetime.

  /users/{id}:
    get:
      summary: Returns a user information.
      responses:
        '200':
          content:
            application/json:
              schema: 
                type: object
                properties:
                  id:
                    type: integer
                    description: The user ID.
                  username:
                    type: string
                    description: The username.
                  created_at:
                    type: string
                    format: date-time
                    description: The created datetime.

  /tokens/{token}:
    get:
      summary: Check a valid user token.
      responses:
        '200':
          content:
            application/json:
              schema: 
                type: object
                properties:
                  id:
                    type: integer
                    description: The user ID.
                  username:
                    type: string
                    description: The username.
                  created_at:
                    type: string
                    format: date-time
                    description: The created datetime.